export interface GraphStep {
  node: string;
  status: "completed" | "failed";
  elapsed_seconds: number;
}
export interface Orchestration {
  engine: "langgraph";
  nodes: string[];
  edges: [string, string][];
  tools: string[];
  memory: { enabled: boolean; max_turns: number };
  tracing: { provider: "langsmith"; enabled: boolean; content: "metadata_only" | "provider_payloads" };
}
export type RuntimeMode = "mock" | "live";
export type KeyGroup = "llm" | "cloudflare";
export interface LiveSettings {
  embedding_source?: "custom" | "workspace";
  embedding_endpoint?: string;
  embedding_model?: string;
  embedding_dimensions?: number;
  embedding_max_input_tokens?: number;
  chat_endpoint: string;
  chat_model: string;
  chat_max_input_tokens: number;
  chat_max_output_tokens: number;
  structured_output: "json_schema" | "json_object" | "text_json";
  output_limit_parameter: "max_tokens" | "max_completion_tokens";
  cloudflare_account_id: string;
  budget_usd: number;
  embedding_input_usd_per_million?: number;
  chat_input_usd_per_million: number;
  chat_output_usd_per_million: number;
}
export interface ProviderProfile {
  key_group?: KeyGroup;
  name: string;
  model: string;
  roles: string[];
}
export interface Payload {
  credentials?: "server" | "browser";
  embedding_mode?: RuntimeMode;
  embedding_source?: "custom" | "workspace";
  byok_profiles?: ProviderProfile[];
  config_fingerprint?: string;
  byok_key_scope?: string;
  [key: string]: unknown;
  id?: string;
  run_id?: string;
  job_id?: string;
  evaluation_id?: string;
  corpus_id?: string;
  conversation_id?: string;
  graph_steps?: GraphStep[];
  orchestration?: Orchestration;
  document_id?: string;
  version_id?: string;
  latest_version_id?: string;
  active_version_id?: string;
  latest_job_id?: string;
  status?: string;
  state?: string;
  stage?: string;
  mode?: string;
  runtime_mode?: string;
  policy_state?: string;
  name?: string;
  filename?: string;
  title?: string;
  text?: string;
  content?: string;
  question?: string;
  dataset?: string;
  model?: string;
  latest_status?: string;
  version_state?: string;
  job_status?: string;
  created_at?: string;
  uploaded_at?: string;
  note?: string;
  disclaimer?: string;
  abstention?: string;
  code?: string;
  variant?: string;
  active_calls?: number;
  chunk_count?: number;
  chunks_count?: number;
  version_count?: number;
  latest_version_no?: number;
  page?: number;
  number?: number;
  max_file_bytes?: number;
  max_upload_bytes?: number;
  live_charged_cost?: number;
  duration_seconds?: number;
  elapsed_seconds?: number;
  repair_count?: number;
  numerator?: number;
  denominator?: number;
  pending?: number;
  responses?: number;
  reviewed?: number;
  rate?: number;
  value?: number;
  worker_total_seconds?: number;
  repair_generation_seconds?: number;
  latency_seconds?: number;
  attempts?: number;
  known_actual_usd?: number;
  unknown_usage_or_cost_attempts?: number;
  duplicate?: boolean;
  retryable?: boolean;
  embedding_space_matches?: boolean;
  fixture_only?: boolean;
  repaired?: boolean;
  qualified?: boolean;
  human_reviewed?: boolean;
  runtime?: Payload;
  policy?: Payload;
  limits?: Payload;
  ingestion?: Payload;
  budgets?: Payload;
  latest_version?: Payload;
  active_version?: Payload;
  progress?: Payload;
  run?: Payload;
  evaluation?: Payload;
  result?: Payload;
  report?: Payload;
  summary?: Payload;
  metrics?: Payload;
  controlled?: Payload | Payload[];
  payload?: Payload;
  timings?: Payload;
  ledger_summary?: Payload;
  version?: string | Payload;
  blocks?: Payload[];
  answer_blocks?: Payload[];
  chunks?: Payload[] | number;
  pages?: number | Payload[];
  extracted_pages?: Payload[];
  errors?: (string | Payload)[];
  items?: Payload[];
  documents?: Payload[];
  corpora?: Payload[];
  runs?: Payload[];
  evaluations?: Payload[];
  jobs?: Payload[];
  citation_ids?: string[];
  ci95_wilson?: number[];
  answer?: string | Payload | Payload[];
  released_answer?: string | Payload | Payload[];
  evidence?: Payload | Payload[];
  evidence_pack?: Payload | Payload[];
  qualification?: string | Payload;
  profiles?: Record<string, string | Payload>;
  variants?: Record<string, Payload> | Payload[];
  variant_metrics?: Record<string, Payload> | Payload[];
  message?: string | Payload;
  detail?: string | Payload;
  error?: string | Payload;
}
export type View = "ask" | "documents" | "evaluations";
